### ISSUE TITLE
How to Add File System Information to Partition Tables

### ISSUE THREAD

**Issue by zzjrabbit** [Quyzi/gpt#102]
I'm using this crate to build a tool to edit edit a disk image in GPT format. But when I used it to create a partition and used parted to read it, I found that the file system information column was empty. I have tried many times to add file system information. But I failed, otherwise I would not write this Issue. Could you please tell me how to add file system information to  the partition tables?

**Comment by gaochuntie** [comment]
You can get raw byte arry of the partition entry and write something.Or you can get byte arry of partition attribute field and set something if there is no existed help function in this crate.Below is the structure of a partition entry on disk.
<html>
<body>

0 (0x00) | 16 bytes | Partition type GUID (mixed endian[11])
-- | -- | --
16 (0x10) | 16 bytes | Unique partition GUID (mixed endian)
32 (0x20) | 8 bytes | First LBA (little endian)
40 (0x28) | 8 bytes | Last LBA (inclusive, usually odd)
48 (0x30) | 8 bytes | Attribute flags (e.g. bit 60 denotes read-only)
56 (0x38) | 72 bytes | Partition name (36 UTF-16LE code units)


</body>
</html>0 (0x00)	16 bytes	[Partition type GUID](https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs) (mixed endian[[11]](https://en.wikipedia.org/wiki/GUID_Partition_Table#cite_note-tn2166-11))
16 (0x10)	16 bytes	Unique partition GUID (mixed endian)
32 (0x20)	8 bytes	First LBA ([little endian](https://en.wikipedia.org/wiki/Little_endian))
40 (0x28)	8 bytes	Last LBA (inclusive, usually odd)
48 (0x30)	8 bytes	Attribute flags (e.g. bit 60 denotes read-only)
56 (0x38)	72 bytes	Partition name (36 [UTF-16](https://en.wikipedia.org/wiki/UTF-16)LE code units)

**Comment by gaochuntie** [comment]
In your case
0 (0x00) 16 bytes Partition type GUID (mixed endian[11])
is what you want to set.You can check the list below and figure out the GUID and then write it at 0x00 of partition entry.
In addition,such fs flag is not so usful,cause you can format a dos flagged partition to unix fs.
https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs

**Comment by soerenmeier** [comment]
You need to set the partition type. For example using add_partition:
```rust
gptdisk.add_partition(
    "linux fs",
    65536,
    // this is the partition type
    gpt::partition_types::LINUX_FS,
    0,
    None
);
```
[partition_types](https://docs.rs/gpt/latest/gpt/partition_types/index.html)

**Comment by soerenmeier** [comment]
Feel free to reopen if something isn't clear
