### ISSUE TITLE
Partition creates empty partition entries

### ISSUE THREAD

**Issue by mzhong1** [Quyzi/gpt#46]
The num_partition from the gpt table header indicates the total number of possible partition array entries -> not the number of actually used partitions.  As such, when partition is called, it creates a tree that has both the actual partitions used and a bunch of empty entries.  Since empty entries are all zeroed, an easy fix is in file_read_partitions (in partition.rs), to check if the bytes read to create a Partition entry in the tree are 0's and skip that entry if so.   See https://metebalci.com/blog/a-quick-tour-of-guid-partition-table-gpt/#gpt-partition-entry-array

**Comment by mzhong1** [comment]
![image](https://user-images.githubusercontent.com/9067743/67294246-91907e80-f4b3-11e9-98c5-08c0ffb10a95.png)
If you run an fdisk on the disk image, you can see that there is only 1 partition, however a GptConfig.partitions().len() on the image returns 128 (the number of partition entries in the table) instead of 1 (the number of used partitions in the table).  Perhaps a fix could be by having a partition_entry() function that returns the partition entries and another that just returns the partitions that are in use?

**Comment by Quyzi** [comment]
I think this has been resolved after your PR. Thanks again
