### ISSUE TITLE
The number of Partition Entries

### ISSUE THREAD

**Issue by gradzik** [Quyzi/gpt#63]
I try to use gpt library, but I don't know how to do one thing. Is there a way to change num_parts in headers?

**Comment by Quyzi** [comment]
`num_parts` by the UEFI model should be a minimum of 128. It's the total number of entries in the partition table, not the number of used partitions.  I've kept it at 128 to maintain compatibility.

**Comment by gradzik** [comment]
Yes, the default is 128, but in embedded systems, I sometimes need to change it, so I was curious how to do this. If modification isn't allowed intentionally, I will look for another solution.
Thanks for the reply.

**Comment by Quyzi** [comment]
I didn't build it in because of compatibility, but if there is a use case I could add an additional fn to create a new header with a variable for num_parts.

**Comment by gradzik** [comment]
It would be very helpful, thanks.

**Comment by Quyzi** [comment]
@gradzik Could you clone into the enable_embedded branch and test it against your use case? I've added a new fn `update_partitions_embedded` that takes a u32 for the number of partitions.

**Comment by gradzik** [comment]
The new function works fine when creating a new partition table, but when resizing the existing partition table first_usable_sector and last_usable_sector don't change. I think it should be updated.

**Comment by Quyzi** [comment]
@gradzik I don't have as much time to dedicate to this project as I used to.  If you would want to submit a PR to add this functionality, I'll approve it and update the crate.

**Comment by oldgalileo** [comment]
Nice work @gradzik! Addressed in PR #68 and merged. This issue should probably be closed.
