### ISSUE TITLE
partition-types: document whether/how codegen works

### ISSUE THREAD

**Issue by lucab** [Quyzi/gpt#8]
I'd like to add support for [CoreOS partition types](https://coreos.com/os/docs/latest/constants-and-ids.html#gpt-partition-types) but I'm not exactly sure what is the procedure, and if there is some code-generation involved.

I see there is a huge JSON array in this repo, and then a lazy-static hashmap in the source code. Is there a scripted process to re-generate the latter from the former? Was the JSON manually assembled or is it coming from some external source?

**Comment by Quyzi** [comment]
I originally wrote the lib to read the json file for partition uuid's but that was much slower than I'd like. We wound up replacing the file with the hashmap. It's easy enough to add new partition types, just append them to the hashmap.
