### ISSUE TITLE
Testing for GPT devices

### ISSUE THREAD

**Issue by andrewbaxter** [Quyzi/gpt#85]
Hello, thanks for this project! I'm not sure if there's a better way, but I was hoping to scan `/dev/block` and test each one to see if it's a GPT drive or not, like
```
for dev in /dev/block/by-path if not ends with "-part" {
    match read_gpt(dev) {
        Ok(Some(info)) => ...
        Ok(None) => continue
        Err(e) => panic(e)
    };
}
```
Right now the library indicates this in an error, but it's part of a human readable string that I wouldn't expect to be part of the specification (could change in a minor version update) so I'm not super comfortable matching on it.

**Comment by soerenmeier** [comment]
If you're still interested, `GptConfig::open` returns now it's own error `GptError`. Does this solve your issue?
https://docs.rs/gpt/4.0.0-rc.1/gpt/struct.GptConfig.html#method.open
https://docs.rs/gpt/4.0.0-rc.1/gpt/enum.GptError.html

**Comment by andrewbaxter** [comment]
Oh nice! Sorry, I haven't been working with this code recently but that looks promising.  So IIUC would `GptError::Header(HeaderError::InvalidGptSignature)` be an appropriate way to separate Gpt and non-Gpt devices?

**Comment by soerenmeier** [comment]
Yes, but i would also consider `GptError::Io` and `GptError::Header(HeaderError::Io)` as an indication that it is not a GPT device. Or more specific `std::io::ErrorKind::UnexpectedEof`, since if the device is not big enough to contain a header, UnexpectedEof will be returned.

**Comment by andrewbaxter** [comment]
Ah okay, right it makes sense that it's ambiguous anyway.  Thanks!
