### ISSUE TITLE
Version 3.0.0 breaks on nightly

### ISSUE THREAD

**Issue by AarSeBail** [Quyzi/gpt#91]
Due to rust-lang/rust#113152, `crc ^1.8` breaks on nightly. A version bump to stabilize Quyzi/gpt#87 should fix this unless I'm mistaken. Build of `gpt 3.0.0` breaks with the following error currently.

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.51/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
```

**Comment by soerenmeier** [comment]
Will see if I can get Chris to publish a new version. In the meantime you could use the newly created branch v3.0.1 https://github.com/Quyzi/gpt/tree/3.0.1

**Comment by soerenmeier** [comment]
A new version 3.1 is now available on crates.io.
