### ISSUE TITLE
Partition::size is of by one

### ISSUE THREAD

**Issue by sjoerdsimons** [Quyzi/gpt#96]
the size function just returns the `<last lba> - <first lba>` as the size, however the last lba is inclusive. So the real size would be `last - first + 1`. The `bytes_len` function interestingly actually gets this right.

Filing an issue rather then a patch directly as users may depend on this behaviour by now, so not sure if this is something to see fixed (rather then documented) in a non-major update

**Comment by soerenmeier** [comment]
Thanks for filing this issue. Since I'm working on a new major version 4.0 let's just fix it there and put it in the release notes.
If you already have a fork feel free to open a PR.

**Comment by soerenmeier** [comment]
I published v4.0.0-rc.2.

Can you use an rc version or do you need a full release?

**Comment by sjoerdsimons** [comment]
rc2 is fine. Thanks!
